#! /bin/env bash

W_FILE="weight.conf"
NGINX_SWARM="canario_load-balancer"

weighs=(25 50 75)


weight_update(){
    local canary_weight=$1
    local weight_stable=$((100 - $canary_weight))

    docker exec -i $(docker container ls --filter name=$NGINX_SWARM -q) sed -i "s/server web-1:5010 weight=[0-9]\+;/server web-1:5010 weight=$weight_stable;/" /etc/nginx/nginx.conf
    docker exec -i $(docker container ls --filter name=$NGINX_SWARM -q) sed -i "s/server web-1:5011 weight=[0-9]\+;/server web-1:5011 weight=$weight_stable;/" /etc/nginx/nginx.conf
    docker exec -i $(docker container ls --filter name=$NGINX_SWARM -q) sed -i "s/server web-2:5010 weight=[0-9]\+;/server web-2:5010 weight=$canary_weight;/" /etc/nginx/nginx.conf
    docker exec -i $(docker container ls --filter name=$NGINX_SWARM -q) sed -i "s/server web-2:5011 weight=[0-9]\+;/server web-2:5011 weight=$canary_weight;/" /etc/nginx/nginx.conf
    docker exec -i $(docker container ls --filter name=$NGINX_SWARM -q) nginx -s reload
    echo "weights updated: \n STABLE: $we||ight_stable \n CANARY: $canary_weight"


}

for w in "${weighs[@]}"; do
    echo "CANARY: $w"
    weight_update $w 
    echo "stabilizing for a couple of moments" 
    sleep 10 # can  be adjusted
done 

echo "canary deployment complete" 
